### PR TITLE
Make sure regular event fields don't get overwritten by attributes

### LINKED ISSUE #47: Attributes with same key as regular fields can cause problems
In the current implementation, nothing prevents clients from sending events with a custom attribute of `{:time "blah"}`.
This causes riemann to crash when using for instance `expired?`.

### PR DESCRIPTION
**Pull request by faxm0dem**
Fixes #47

### CODE REVIEW

**Comment by faxm0dem** [comment]
Maybe string attributes should stay out of the blacklist ?
Problems only appear for numeric fields (metric, time and ttl)

**Comment by faxm0dem** [comment]
I'd also add the `tags` attribute as it would mess things up too (it's a vector in riemann), what do you think ?

**Comment by faxm0dem** [comment]
Sorry to poke you all ;-) but does this look good to you?

**Comment by jamtur01** [comment]
Ah sorry - I totally missed your update. Looks good and thanks!

**Pull request merged**
